export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const RESET_PASSWORD="RESET_PASSWORD";
export const FORGOT_PASSWORD_REQUEST_SUCCESS="FORGOT_PASSWORD_REQUEST_SUCCESS";
export const FORGOT_PASSWORD_REQUEST_FAIL="FORGOT_PASSWORD_REQUEST_FAIL";

export const RESET_PASSWORD_REQUEST_SUCCESS="RESET_PASSWORD_REQUEST_SUCCESS";
export const RESET_PASSWORD_REQUEST_FAIL="RESET_PASSWORD_REQUEST_FAIL";

export const UPDATE_STOCK_REQUEST_SUCCESS="UPDATE_STOCK_REQUEST_SUCCESS";
export const UPDATE_STOCK_REQUEST_FAIL="UPDATE_STOCK_REQUEST_FAIL";


export const GET_BENEFICE_SUCCESS="GET_BENEFICE_SUCCESS";

export const SET_BASKET_RECTIFICATION_ITEMS = 'SET_BASKET_ITEMS_RECTIFICATION';
export const ADD_TO_BASKET_RECTIFICATION = 'ADD_TO_BASKET_RECTIFICATION';
export const REMOVE_FROM_BASKET_RECTIFICATION = 'REMOVE_FROM_BASKET_RECTIFICATION';
export const CLEAR_BASKET_RECTIFICATION = 'CLEAR_BASKET_RECTIFICATION';
export const ADD_QTY_ITEM_RECTIFICATION = 'ADD_QTY_ITEM_RECTIFICATION';
export const MINUS_QTY_ITEM_RECTIFICATION = 'MINUS_QTY_ITEM_RECTIFICATION';


export const SET_VERSION_INFO = "SET_VERSION_INFO";
export const SET_IGNORE_VERSION = "SET_IGNORE_VERSION";