export const ROLES = {
  admin: "ADMIN",
  vendeurLV1: "VENDEURLV1",
  vendeurLV2: "VENDEURL2",
};
export const SCOPES = {
  canShowDashboard: "can-view-dashboard",
  canShowFactureProducts: "can-show-facture-products",
  canShowFactures: 'can-show-factures',
  canShowProducts: 'can-show-products',
  canShowDepot: 'can-show-depot',
  canShowBonDeSortie: 'can-show-bon-de-sortie',
  canShowHistoriqueDeSortie: 'can-show-historique-de-sortie',
  canShowCredit: 'can-show-credit',
  canShowVaccinateur: 'can-show-vaccinateur',
  canShowMagasin: 'can-show-magasin',
  canShowDepotVersMagasin: 'can-show-depot-vers-magasin',
  canHistoriqueDeDM: 'can-show-historique-de-dm',
  canShowCorrection: 'can-show-correction',
  canAddCorrection: 'can-add-correction',
  canShowHistoriqueDeCorrection: 'can-show-historique-de-correction',
  canShowVente: 'can-show-vente',
  canShowEffectuerUneVente: 'can-show-effectuer-une-vente',
  canShowEtatDeStockMagasin: 'can-show-etat-de-stock-magasin',
  canShowHistoriqueDeVenteDuMagasin: 'can-show-historique-de-vente-du-magasin',
  canShowVenteCredit: 'can-show-vente-credit',
  canShowParameter: 'can-show-parameter',
  canShowCategory: 'can-show-category',
  canShowFournisseur: 'can-show-fournisseur',
  canShowDemandeurCredit: 'can-show-demandeur-credit',
  canShowVaccinateurs: 'can-show-vaccinateurs',
  canShowDetailFactures: 'can-show-detail-factures',
  canShowEditFacture: 'can-show-edit-facture',
  canShowAddFacture: 'can-show-add-facture',
  canShowDeleteFacture: 'can-show-delete-facture',
  canShowDetailProduit: 'can-show-detail-produit',
  canShowEditProduit: 'can-show-edit-produit',
  canShowAddProduit: 'can-show-add-produit',
  canShowDeleteProduit: 'can-show-delete-produit',
  canShowDetailCreditDepot: 'can-show-detail-credit-depot',
  canShowEditCreditDepot: 'can-show-edit-credit-depot',
  canShowAddCreditDepot: 'can-show-add-credit-depot',
  canShowDeleteCreditDepot: 'can-show-delete-credit-depot',
  canShowDetailVaccinateurCreditDepot: 'can-show-detail-vaccinateur-credit-depot',
  canShowEditVaccinateurCreditDepot: 'can-show-edit-vaccinateur-credit-depot',
  canShowAddVaccinateurCreditDepot: 'can-show-add-vaccinateur-credit-depot',
  canShowDeleteVaccinateurCreditDepot: 'can-show-delete-vaccinateur-credit-depot',
  canShowDetailHistoricDeSortieDepot: 'can-show-detail-historic-de-sortie-depot',
  canShowEditHistoricDeSortieDepot: 'can-show-edit-historic-de-sortie-depot',
  canShowAddHistoricDeSortieDepot: 'can-show-add-historic-de-sortie-depot',
  canShowDeleteHistoricDeSortieDepot: 'can-show-delete-historic-de-sortie-depot',
  //canCreate: "can-create",
  // canEdit: "can-edit",
  // canDelete: "can-delete",
   //canView: "can-view",
  canCreateCategory: "can-create-category",
  canEditCategory: "can-edit-category",
  canDeleteCategory: "can-delete-category",
  canViewCategory: "can-view-category",
  canCreateEmprunter: "can-create-emprunter",
  canEditEmprunter: "can-edit-emprunter",
  canDeleteEmprunter: "can-delete-emprunter",
  canViewEmprunter: "can-view-emprunter",
  canCreateFournisseurs: "can-create-fournisseurs",
  canEditFournisseurs: "can-edit-fournisseurs",
  canDeleteFournisseurs: "can-delete-fournisseurs",
  canViewFournisseurs: "can-view-fournisseurs",
  canCreateVaccinateur: "can-create-vaccinateur",
  canEditVaccinateur: "can-edit-vaccinateur",
  canDeleteVaccinateur: "can-delete-vaccinateur",
  canViewVaccinateur: "can-view-vaccinateur",
  canCreate: "can-create",
  canEdit: "can-edit",
  canDelete: "can-delete",
  canView: "can-view",
};

export const PERMISSIONS = {
  [ROLES.admin]: [
    SCOPES.canShowDashboard,
    SCOPES.canShowFactureProducts,
    SCOPES.canShowFactures,
    SCOPES.canShowProducts,
    SCOPES.canShowDepot,
    SCOPES.canShowBonDeSortie,
    SCOPES.canShowHistoriqueDeSortie,
    SCOPES.canShowCredit,
    SCOPES.canShowVaccinateur,
    SCOPES.canShowMagasin,
    SCOPES.canShowDepotVersMagasin,
    SCOPES.canAddCorrection,
    SCOPES.canShowVente,
    SCOPES.canShowEffectuerUneVente,
    SCOPES.canShowEtatDeStockMagasin,
    SCOPES.canShowHistoriqueDeVenteDuMagasin,
    SCOPES.canShowVenteCredit,
    SCOPES.canShowParameter,
    SCOPES.canShowCategory,
    SCOPES.canShowFournisseur,
    SCOPES.canShowDemandeurCredit,
    SCOPES.canShowVaccinateurs,
    SCOPES.canShowDetailFactures,
    SCOPES.canShowEditFacture,
    SCOPES.canShowAddFacture,
    SCOPES.canShowDeleteFacture,
    SCOPES.canShowDetailProduit,
    SCOPES.canShowEditProduit,
    SCOPES.canShowAddProduit,
    SCOPES.canShowDeleteProduit,
    SCOPES.canShowDetailCreditDepot,
    SCOPES.canShowEditCreditDepot,
    SCOPES.canShowAddCreditDepot,
    SCOPES.canShowDeleteCreditDepot,
    SCOPES.canShowDetailHistoricDeSortieDepot,
    SCOPES.canShowEditHistoricDeSortieDepot,
    SCOPES.canShowAddHistoricDeSortieDepot,
    SCOPES.canShowDeleteHistoricDeSortieDepot,
    SCOPES.canShowDetailVaccinateur,
    SCOPES.canShowEditVaccinateur,
    SCOPES.canShowAddVaccinateur,
    SCOPES.canShowDeleteVaccinateur,
    SCOPES.canShowDetailVaccinateurCreditDepot,
    SCOPES.canShowEditVaccinateurCreditDepot,
    SCOPES.canShowAddVaccinateurCreditDepot,
    SCOPES.canShowDeleteVaccinateurCreditDepot,
    SCOPES.canCreateCategory,
    SCOPES.canEditCategory,
    SCOPES.canDeleteCategory,
    SCOPES.canCreateFournisseurs,
    SCOPES.canEditFournisseurs,
    SCOPES.canDeleteFournisseurs,
    SCOPES.canCreateEmprunter,
    SCOPES.canEditEmprunter,
    SCOPES.canDeleteEmprunter,
    SCOPES.canCreateVaccinateur,
    SCOPES.canEditVaccinateur,
    SCOPES.canDeleteVaccinateur,
    SCOPES.canHistoriqueDeDM,
    SCOPES.canShowCorrection,
    SCOPES.canAddCorrection,
    SCOPES.canShowHistoriqueDeCorrection,

  ],
  [ROLES.vendeurLV1]: [],
  [ROLES.vendeurLV2]: []
};