export const HOME = '/';
export const APPROV = '/approv';
export const CREATEPRODUCT ='/create-product';
export const EDITPRODUCT = `/product/edit/:id`;
export const PRODUCTS='/products';
export const PERIME = '/perimes';
export const RUPTURE = '/rupture';
export const CREDIT = '/credit';
export const DETAIL = `/detail/:id`;
export const DETAILVENDEUR = `/detailvendeur/:id`
export const CREDITVACCINATEUR ='/credit/vaccinateur'
export const DIRECT ='/direct'
export const JOURNAL ="/journal";
export const PARAMETRES ="/parametres";
export const PRODUCTBYFOURNISSEUR = '/product/fournisseur';
export const PRODUCTBYCATEGORY = '/product/category';
export const PARASUPPL = '/para/suppl';
export const ENTREE = '/entree';
export const SORTIE = '/sortie';
export const BONDESORTIE='/bon/sortie';
export const PRODUCTDETAIL=`/product/detail/:id`;
export const BSORTIE = '/b/sortie';
export const ADDPROD = '/add/prod';

export const NOUVELLEFACTURE = "/nouvelle/facture";
export const EDITERFACTURE ='/editer/facture/:id';
export const DETAILAPPROV = "/approvis/detail/:id";
export const LISTAPPROV = "/list/approv"

export const SIGNIN = '/signin';
export const SIGNOUT = '/signout';
export const SIGNUP = '/signup';
export const VENDEUR ='/vendeur';
export const ADMIN ="/admin";
export const DEPOTOMAGASIN="depot/to/magasin/";
export const HISTORIQUESORTIECVA = '/historique/sortie/cva';
export const HISTORIQUEVENTEVENDEUR ='/historique/vente/vendeur';
export const HISTORIQUEVENTEVENDEURVUEPARADMIN='/historique/vente/admin/vendeur'
export const ETATSTOCKMAGASIN = '/etat/stock/magasin';