export const SET_APPROV_ITEMS = 'SET_APPROV_ITEMS';
export const ADD_TO_APPROV = 'ADD_TO_APPROV';
export const REMOVE_FROM_APPROV = 'REMOVE_FROM_APPROV';
export const CLEAR_APPROV = 'CLEAR_APPROV';
export const ADD_QTY_APPROV_ITEM = 'ADD_QTY_APPROV_ITEM';
export const MINUS_QTY_APPROV_ITEM = 'MINUS_QTY_APPROV_ITEM';
export const ADD_NUMBER_QTY_ITEM ='ADD_NUMBER_QTY_ITEM';
export const ADD_QTY_NUMBER_APPROV_ITEM = 'ADD_QTY_NUMBER_APPROV_ITEM'