export const SET_BASKET_ITEMS = 'SET_BASKET_ITEMS';
export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET';
export const CLEAR_BASKET = 'CLEAR_BASKET';
export const ADD_QTY_ITEM = 'ADD_QTY_ITEM';
export const MINUS_QTY_ITEM = 'MINUS_QTY_ITEM';
export const ADD_QTY_PORTION_ITEM = 'ADD_QTY_PORTION_ITEM';
export const MINUS_QTY_PORTION_ITEM = 'MINUS_QTY_PORTION_ITEM';

export const SET_CHECKOUT_SHIPPING_DETAILS = 'SET_CHECKOUT_SHIPPING_DETAILS';
export const SET_CHECKOUT_PAYMENT_DETAILS = 'SET_CHECKOUT_PAYMENT_DETAILS';
export const RESET_CHECKOUT = 'RESET_CHECKOUT';
