export const SET_TO_MAGASIN_ITEMS = 'SET_TO_MAGASIN_ITEMS';
export const ADD_TO_MAGASIN = 'ADD_TO_MAGASIN';
export const REMOVE_FROM_MAGASIN = 'REMOVE_FROM_MAGASIN';
export const CLEAR_MAGASIN = 'CLEAR_MAGASIN';
export const ADD_QTY_MAGASIN_ITEM = 'ADD_QTY_MAGASIN_ITEM';
export const MINUS_QTY_MAGASIN_ITEM = 'MINUS_QTY_MAGASIN_ITEM';
export const ADD_NUMBER_QTY_ITEM ='ADD_NUMBER_QTY_ITEM';
export const ADD_QTY_NUMBER_MAGASIN_ITEM="ADD_QTY_NUMBER_MAGASIN_ITEM";