name: Build and Release Windows App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build Electron App
      run: npm run build

    - name: Create Windows Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./dist/win-unpacked/**
        token: ${{ secrets.GITHUB_TOKEN }}
