name: Electron Build

on:
  push:
    branches:
      - main
  pull_request:

env:
  ELECTRON_CACHE: ${{ runner.os }}-electron-cache
  ELECTRON_BUILDER_CACHE: ${{ runner.os }}-electron-builder-cache

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: |
          npm install
          npm install --only=dev
      
      - name: Build Electron App
        run: |
          npm run build
          npm run electron:build -- --win
  
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-electron-app-windows
          path: dist/electron-builder/my-electron-app Setup 1.0.0.exe
